services:
  web-catalogue:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    image: urbanscratcher/web-catalogue:latest
    ports:
      - "3000:3000"
    volumes:
      - ./.env:/usr/src/app/.env
